version: "3.8"

services:

  web:
    build: .
    command:
      ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 6666:5432
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A KeyManager worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
  
  celery-beat:
    build: .
    command: celery -A KeyManager beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data: