# Generated by Django 5.0.6 on 2024-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_school_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
