# Generated by Django 5.0.6 on 2024-05-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_accesskey_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
